CREATE TABLE DAILY_USAGE_TGT (
    METER_ID      VARCHAR2(100),
    USAGE_DATE    DATE,
    DAILY_USAGE   NUMBER(10,2)
);
CREATE TABLE CONSUMPTION_ALERTS (
    meter_id        VARCHAR2(20),
    usage_date      DATE,
    daily_usage     NUMBER,
    alert_flag      VARCHAR2(5),
    alert_message   VARCHAR2(100)
);
CREATE TABLE TGT_LOW_VOLTAGE_ALERT (
    METER_ID        VARCHAR2(20),
    CUSTOMER_ID     VARCHAR2(20),
    CUSTOMER_NAME   VARCHAR2(100),
    EMAIL_ID        VARCHAR2(100),
    VOLTAGE         NUMBER
);
select *from consumption_alerts;
CREATE TABLE CUSTOMER_PEAK_USAGE (
    CUSTOMER_ID    VARCHAR2(100),
    CUSTOMER_NAME  VARCHAR2(255),
    PEAK_USAGE     NUMBER,
    PEAK_DATE      DATE,
    PEAK_HOUR      VARCHAR2(5)
);
CREATE TABLE STG_MASTER_METER (
    C_POWER_FACTOR    VARCHAR2(
    C_METER_ID        VARCHAR2(255),255),
    C_VOLTAGE_LEVEL   VARCHAR2(255),
    C_DATE            VARCHAR2(255),

    C_POWER_FACTOR_DEC NUMBER(10,2),
    C_VOLTAGE_DEC      NUMBER(10),

    C_RECORD_STATUS   VARCHAR2(50),
    C_ERROR_REASON    VARCHAR2(255),

    CUSTOMER_ID       VARCHAR2(100),
    EMAIL_ID          VARCHAR2(255),
    CUSTOMER_NAME     VARCHAR2(255),

    METER_ID          VARCHAR2(100)
);

INSERT INTO DAILY_USAGE_TGT (METER_ID, USAGE_DATE, DAILY_USAGE)
SELECT 
    METER_ID,
    TRUNC(C_DATE_CONV) AS USAGE_DATE,
    SUM(C_VOLTAGE_DEC) AS DAILY_USAGE
FROM STG_MASTER_METER
WHERE C_RECORD_STATUS = 'VALID'
GROUP BY METER_ID, TRUNC(C_DATE_CONV);
select *from CUSTOMER_PEAK_USAGE;
alter table CUSTOMER_PEAK_USAGE drop column peak_hour;
select *from consumption_alerts;